enabled = true
version = 2

[[entry]]
	ip = "localhost"
	description = "Играет на Локальном Сервере"
	state = ""
	largeImageKey = "mclogo"
	largeImageText = "Fabric %mcver%"
	smallImageKey = ""
	smallImageText = ""

[[entry]]
	ip = "prp.plo.su"
	description = "Играет на Plasmo RP"
	state = ""
	largeImageKey = ""
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""
	
[[entry]]
	ip = "crp.plo.su"
	description = "Играет на Plasmo RP Creative"
	state = ""
	largeImageKey = ""
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""	

[[entry]]
	ip = "lanterdam.aboba.host"
	description = "Играет на Lanterdam Test"
	state = ""
	largeImageKey = "allay"
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""

[[entry]]
	ip = "totems.aboba.host"
	description = "Играет на Totems SMP"
	state = ""
	largeImageKey = "totems_smp"
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""










	