
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	applicationID = 935490361239953408
	enabled = true
	debugging = false
	configScreen = false
	launcherIntegration = false
	version = 18

[init]
	enabled = true
	description = "Майнкрафт запускается..."
	state = ""
	largeImageKey = ["mclogo"]
	largeImageText = "Fabric %mcver%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[main_menu]
	enabled = true
	description = "%player% отдыхает в меню"
	state = ""
	largeImageKey = ["mclogo"]
	largeImageText = "Fabric %mcver%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[server_list]
	enabled = true
	description = "%player% в меню серверов"
	state = ""
	largeImageKey = ["mclogo"]
	largeImageText = "Fabric %mcver%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[realms_list]
	enabled = true
	description = "%player% смотрит на Realms"
	state = ""
	largeImageKey = ["mclogo"]
	largeImageText = "Fabric %mcver%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[join_game]
	enabled = true
	description = "%player% присоединяется к игре"
	state = ""
	largeImageKey = ["mclogo"]
	largeImageText = "Fabric %mcver%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[single_player]
	enabled = true
	description = "Играет в одиночестве"
	state = "Мир: %savename%"
	largeImageKey = ["mclogo"]
	largeImageText = "Fabric %mcver%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[multi_player]
	enabled = true
	description = "Играет на %servername%"
	state = "Онлайн: %players% / %maxplayers%"
	largeImageKey = ["%servericon%"]
	largeImageText = "%serverip%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[realms]
	enabled = true
	description = "Играет на %realmname%"
	state = "Онлайн: %players% / %maxplayers%"
	largeImageKey = ["%realmicon%"]
	largeImageText = "%realmname%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[generic]
	description = "Играет в Майнкрафт"
	state = ""
	largeImageKey = ["mclogo"]
	largeImageText = "Fabric %mcver%"
	smallImageKey = [""]
	smallImageText = ""
	buttons = []

[custom]
	enabled = true
	variables = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = ["overworld"]
		largeImageText = "In the Overworld"
		smallImageKey = [""]
		smallImageText = ""
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = ["nether"]
		largeImageText = "In the Nether"
		smallImageKey = [""]
		smallImageText = ""
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = ["end"]
		largeImageText = "In the End"
		smallImageKey = [""]
		smallImageText = ""
		buttons = []

